### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by fauzianggoro** [project-garden/project-garden-frontend#8]
# Javascript Plan

* 1st Week

  - [x] Data Structure (monday)
  - [x] Function (thuesday-wednesday)
  - [ ] OOP (thursday-friday)
  - [ ] Get your inspire (saturday-sunday) 

* 2nd Week

  - [ ] Functional Programming (monday-thuesday)
  - [ ] Setup Environtment (wednesday)
  - [ ] Modul (thursday)
  - [ ] Error Handling (friday)
  - [ ] Get your inspire (saturday-sunday) 

* 3rd Week

  - [ ] Concurrency (monday-thusday)
  - [ ] NPM (wednesday)
  - [ ] Javascript Testing (thursday-friday)
  - [ ] Get your inspire (saturday-sunday) 

* 4th Week

  - [ ] Save time or starting project

# React JS Plan

* 1st Week

  - [x] Get started with React (monday-thusday)
  - [ ] Describing the UI (wednesday-friday)

* 2nd Week

  - [ ] Adding Interactivity (all weekday)

* 3rd Week

  - [ ] Managing State (all weekday)

* 4th Week

  - [ ] Escape Hatches (all weekday)

**Comment by fauzianggoro** [comment]
for react learn modul, soon to describe all weekday target

**Comment by Hazunanafaru** [comment]
Nice! Good Luck with  ur journey 🚀🚀🚀

**Comment by fauzianggoro** [comment]
Bismillah lurr, alon alon temenan kelakon wkwk
